apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <body>
    <main>
    <h1>This is Deployment One</h1>
    </main>
    </body>
    </html>