#YAML file for two NGINX app deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy01
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-cont01
        image: nginx:1.23.3
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-vol01
            mountPath: /usr/share/nginx/html
      volumes:
      - name: config-vol01
        configMap:
          name: configmap1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-cont02
        image: nginx:1.23.3
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-vol02
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-vol02
        configMap:
          name: configmap2